export { default as HomePage } from './HomePage'
export { default as NotFoundPage } from './NotFoundPage'
export { default as NotesPage } from './NotesPage'
export { default as TimerPage } from './TimerPage'
export { default as LoginRegister } from './LoginRegisterPage'
export {default as PlannerPage } from './PlannerPage'
